_BASE_: "Base-Keypoint-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "best_model.pth"
  RESNETS:
    DEPTH: 50
  ROI_KEYPOINT_HEAD:
    NUM_KEYPOINTS: 16
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.7
DATASETS:
  TEST: ("sports_1st_test",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.02
  STEPS: (6000, 8000)
  MAX_ITER: 10000
  ROOT_DIR: /
OUTPUT_DIR: outputs
TEST:
  KEYPOINT_OKS_SIGMAS: [0.26, 0.045, 0.055, 0.079, 0.079, 0.072, 0.072, 0.062, 0.062, 0.065, 0.107, 0.107, 0.087, 0.087, 0.089, 0.089]